// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    BorderContainer: typeof import('./src/components/container/BorderContainer.vue')['default']
    Container: typeof import('./src/components/widget/Container.vue')['default']
    ContainerTemplate: typeof import('./src/components/templates/ContainerTemplate.vue')['default']
    ImageTemplate: typeof import('./src/components/templates/ImageTemplate.vue')['default']
    NoticeTemplate: typeof import('./src/components/templates/NoticeTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideshowTemplate: typeof import('./src/components/templates/SlideshowTemplate.vue')['default']
    TextTemplate: typeof import('./src/components/templates/TextTemplate.vue')['default']
    Widget: typeof import('./src/components/widget/Widget.vue')['default']
  }
}

export {}
