// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AResizeBox: typeof import('@arco-design/web-vue')['ResizeBox']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    BorderContainer: typeof import('./src/components/container/BorderContainer.vue')['default']
    ContainerTemplate: typeof import('./src/components/templates/ContainerTemplate.vue')['default']
    ControlBox: typeof import('./src/components/controls/ControlBox.vue')['default']
    ImageTemplate: typeof import('./src/components/templates/ImageTemplate.vue')['default']
    ImageUpload: typeof import('./src/components/controls/ImageUpload.vue')['default']
    NoticeTemplate: typeof import('./src/components/templates/NoticeTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideshowTemplate: typeof import('./src/components/templates/SlideshowTemplate.vue')['default']
    StyleControl: typeof import('./src/components/controls/StyleControl.vue')['default']
    TextControl: typeof import('./src/components/controls/TextControl.vue')['default']
    TextTemplate: typeof import('./src/components/templates/TextTemplate.vue')['default']
    TransitionContainer: typeof import('./src/components/container/TransitionContainer.vue')['default']
    VaResizeBox: typeof import('./src/components/resizebox/VaResizeBox.vue')['default']
  }
}

export {}
